# Generated by Django 5.1.2 on 2024-10-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('unique_code', models.IntegerField(null=True)),
                ('answer_1_question_1', models.TextField()),
                ('answer_2_question_1', models.TextField()),
                ('correct_answer_1', models.TextField()),
                ('answer_1_question_2', models.TextField()),
                ('answer_2_question_2', models.TextField()),
                ('correct_answer_2', models.TextField()),
                ('answer_1_question_3', models.TextField()),
                ('answer_2_question_3', models.TextField()),
                ('correct_answer_3', models.TextField()),
                ('answer_1_question_4', models.TextField()),
                ('answer_2_question_4', models.TextField()),
                ('correct_answer_4', models.TextField()),
                ('answer_1_question_5', models.TextField()),
                ('answer_2_question_5', models.TextField()),
                ('correct_answer_5', models.TextField()),
            ],
        ),
    ]
